// Theme configurations for all 5 themes
// Each theme defines colors, fonts, thematic copy, images, and particle effects

import bgGoT from '../assets/background.png';
import bgHP from '../assets/bg-harrypotter.png';
import bgNetflix from '../assets/bg-netflix.png';
import bgCyberpunk from '../assets/bg-cyberpunk.png';
import bgDemonSlayer from '../assets/bg-demonslayer.png';

import profileGoT from '../assets/profile-got.png';
import profileHP from '../assets/profile-hp.png';
import profileNetflix from '../assets/profile-netflix.png';
import profileCyberpunk from '../assets/profile-cyberpunk.png';
import profileDemonSlayer from '../assets/profile-demonslayer.png';

import logoGoT from '../assets/logo-got.png';
import logoHP from '../assets/logo-hp.png';
import logoNetflix from '../assets/logo-netflix.png';
import logoCyberpunk from '../assets/logo-cyberpunk.png';
import logoDemonSlayer from '../assets/logo-demonslayer.png';

const themes = {
  got: {
    id: 'got',
    name: 'Game of Thrones',
    icon: '🐉',
    background: bgGoT,
    profilePic: profileGoT,
    logo: logoGoT,
    fonts: {
      heading: "'Cinzel', 'Georgia', serif",
      body: "'Lato', sans-serif",
    },
    colors: {
      '--theme-primary': '#D97706',
      '--theme-primary-hover': '#F59E0B',
      '--theme-secondary': '#92400E',
      '--theme-bg': '#111827',
      '--theme-bg-dark': '#000000',
      '--theme-card': 'rgba(31, 41, 55, 0.5)',
      '--theme-card-border': 'rgba(146, 64, 14, 0.3)',
      '--theme-card-hover-border': '#D97706',
      '--theme-card-hover-bg': 'rgba(146, 64, 14, 0.2)',
      '--theme-text': '#F3F4F6',
      '--theme-text-muted': '#9CA3AF',
      '--theme-text-subtle': '#6B7280',
      '--theme-glow': 'rgba(245, 158, 11, 0.5)',
      '--theme-nav-bg': 'rgba(0,0,0,0.9)',
      '--theme-overlay-from': 'rgba(0,0,0,0.7)',
      '--theme-overlay-via': 'rgba(0,0,0,0.5)',
      '--theme-overlay-to': 'rgba(0,0,0,0.9)',
      '--theme-ring': 'rgba(120, 53, 15, 0.5)',
      '--theme-gradient-from': '#000000',
      '--theme-gradient-to': '#111827',
    },
    copy: {
      tagline: 'Forged by Logic',
      about: "I am Ajay Garg — a warrior of code forged in the fires of logic and tempered by relentless pursuit of excellence. Like the great houses of Westeros, I believe in honor, dedication, and the power of building strong alliances. My journey through the realm of technology has been guided by curiosity, the will to conquer complex challenges, and the wisdom to craft digital experiences that stand the test of time.",
      aboutTitle: 'My Oath and History',
      skillsTitle: 'Skills: My Arsenal',
      educationTitle: "Education: My Maester's Training",
      interestsTitle: 'Interests: What I Seek',
      resumeTitle: 'The Chronicle (Resume)',
      resumeDesc: 'Download my complete chronicle to witness my professional journey, training, and achievements.',
      resumeButton: 'Download Chronicle',
      contactTitle: 'Contact The House',
      contactDesc: "Let's connect! Send a raven through any of these platforms.",
      heroButton1: 'Learn My History',
      heroButton2: 'Contact The House',
      footerLine: 'The Code is My Word.',
      footerQuote: '"When you play the game of codes, you win or you get bugged."',
    },
    particles: {
      type: 'embers',
      color: '#D97706',
      count: 25,
    },
  },

  harrypotter: {
    id: 'harrypotter',
    name: 'Harry Potter',
    icon: '⚡',
    background: bgHP,
    profilePic: profileHP,
    logo: logoHP,
    fonts: {
      heading: "'Playfair Display', 'Georgia', serif",
      body: "'Lato', sans-serif",
    },
    colors: {
      '--theme-primary': '#C9A84C',
      '--theme-primary-hover': '#E2C76A',
      '--theme-secondary': '#4A1A6B',
      '--theme-bg': '#0F0A1E',
      '--theme-bg-dark': '#070412',
      '--theme-card': 'rgba(74, 26, 107, 0.25)',
      '--theme-card-border': 'rgba(74, 26, 107, 0.4)',
      '--theme-card-hover-border': '#C9A84C',
      '--theme-card-hover-bg': 'rgba(74, 26, 107, 0.35)',
      '--theme-text': '#E8DCC8',
      '--theme-text-muted': '#B8A88A',
      '--theme-text-subtle': '#7A6B55',
      '--theme-glow': 'rgba(201, 168, 76, 0.5)',
      '--theme-nav-bg': 'rgba(7, 4, 18, 0.92)',
      '--theme-overlay-from': 'rgba(15, 10, 30, 0.75)',
      '--theme-overlay-via': 'rgba(15, 10, 30, 0.5)',
      '--theme-overlay-to': 'rgba(7, 4, 18, 0.92)',
      '--theme-ring': 'rgba(74, 26, 107, 0.5)',
      '--theme-gradient-from': '#070412',
      '--theme-gradient-to': '#0F0A1E',
    },
    copy: {
      tagline: 'Crafted by Magic',
      about: "I am Ajay Garg — a wizard of the digital realm who received his acceptance letter to the world of code. Like a student at Hogwarts mastering spells, I have devoted myself to learning the arcane arts of web development, conjuring interfaces that feel truly magical. Every line of code I write is a carefully crafted incantation, and every project is a new adventure in a castle full of endless possibilities. Mischief managed, bugs vanquished.",
      aboutTitle: 'The Unbreakable Vow',
      skillsTitle: 'My Spellbook',
      educationTitle: 'Hogwarts Training',
      interestsTitle: 'Magical Pursuits',
      resumeTitle: "The Marauder's Map",
      resumeDesc: 'I solemnly swear that I am up to good — explore my professional journey and achievements.',
      resumeButton: 'Reveal the Map',
      contactTitle: 'Send an Owl',
      contactDesc: "The owlery is open — reach me through any of these magical channels.",
      heroButton1: 'Explore My Magic',
      heroButton2: 'Send an Owl',
      footerLine: 'Mischief Managed.',
      footerQuote: '"After all this time? Always." — Writing code since day one.',
    },
    particles: {
      type: 'sparkles',
      color: '#C9A84C',
      count: 30,
    },
  },

  netflix: {
    id: 'netflix',
    name: 'Netflix',
    icon: '🎬',
    background: bgNetflix,
    profilePic: profileNetflix,
    logo: logoNetflix,
    fonts: {
      heading: "'Bebas Neue', 'Impact', sans-serif",
      body: "'Inter', sans-serif",
    },
    colors: {
      '--theme-primary': '#E50914',
      '--theme-primary-hover': '#FF1A25',
      '--theme-secondary': '#831010',
      '--theme-bg': '#141414',
      '--theme-bg-dark': '#000000',
      '--theme-card': 'rgba(35, 35, 35, 0.7)',
      '--theme-card-border': 'rgba(229, 9, 20, 0.2)',
      '--theme-card-hover-border': '#E50914',
      '--theme-card-hover-bg': 'rgba(229, 9, 20, 0.1)',
      '--theme-text': '#FFFFFF',
      '--theme-text-muted': '#B3B3B3',
      '--theme-text-subtle': '#808080',
      '--theme-glow': 'rgba(229, 9, 20, 0.5)',
      '--theme-nav-bg': 'rgba(0, 0, 0, 0.92)',
      '--theme-overlay-from': 'rgba(0, 0, 0, 0.8)',
      '--theme-overlay-via': 'rgba(0, 0, 0, 0.5)',
      '--theme-overlay-to': 'rgba(20, 20, 20, 0.95)',
      '--theme-ring': 'rgba(229, 9, 20, 0.3)',
      '--theme-gradient-from': '#000000',
      '--theme-gradient-to': '#141414',
    },
    copy: {
      tagline: 'Now Streaming',
      about: "I am Ajay Garg — a developer whose story unfolds like a binge-worthy series. Each project is a new season, every challenge a plot twist, and every deployment is a season finale that keeps the audience wanting more. I produce premium digital experiences with cinematic attention to detail, direct complex codebases with creative vision, and always deliver content that's worth streaming. Grab your popcorn — this production is just getting started.",
      aboutTitle: 'The Synopsis',
      skillsTitle: 'Featured Skills',
      educationTitle: 'Origin Story',
      interestsTitle: 'Also Trending',
      resumeTitle: 'Full Credits',
      resumeDesc: 'Download the complete credits of my professional production.',
      resumeButton: 'Download Credits',
      contactTitle: "Let's Connect",
      contactDesc: 'Ready to collaborate? Reach out through any of these channels.',
      heroButton1: 'Watch My Story',
      heroButton2: 'Get In Touch',
      footerLine: 'Streaming excellence since day one.',
      footerQuote: '"Are you still watching?" — Yes, still coding.',
    },
    particles: {
      type: 'cinematic',
      color: '#E50914',
      count: 15,
    },
  },

  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk City',
    icon: '🌃',
    background: bgCyberpunk,
    profilePic: profileCyberpunk,
    logo: logoCyberpunk,
    fonts: {
      heading: "'Orbitron', sans-serif",
      body: "'Rajdhani', sans-serif",
    },
    colors: {
      '--theme-primary': '#00F0FF',
      '--theme-primary-hover': '#33F5FF',
      '--theme-secondary': '#FF00E5',
      '--theme-bg': '#0A0A1A',
      '--theme-bg-dark': '#050510',
      '--theme-card': 'rgba(10, 10, 40, 0.6)',
      '--theme-card-border': 'rgba(0, 240, 255, 0.2)',
      '--theme-card-hover-border': '#00F0FF',
      '--theme-card-hover-bg': 'rgba(0, 240, 255, 0.08)',
      '--theme-text': '#E0E0FF',
      '--theme-text-muted': '#8888CC',
      '--theme-text-subtle': '#5555AA',
      '--theme-glow': 'rgba(0, 240, 255, 0.5)',
      '--theme-nav-bg': 'rgba(5, 5, 16, 0.92)',
      '--theme-overlay-from': 'rgba(5, 5, 16, 0.7)',
      '--theme-overlay-via': 'rgba(10, 10, 26, 0.5)',
      '--theme-overlay-to': 'rgba(5, 5, 16, 0.92)',
      '--theme-ring': 'rgba(255, 0, 229, 0.3)',
      '--theme-gradient-from': '#050510',
      '--theme-gradient-to': '#0A0A1A',
    },
    copy: {
      tagline: 'System.Online',
      about: "OPERATOR: Ajay_Garg // STATUS: Active // CLEARANCE: Maximum. I am a netrunner navigating the sprawling digital metropolis, jacked into the grid of modern web development. My neural implants run JavaScript at the speed of thought, my cyberdeck compiles React components in milliseconds, and my encrypted connections span every cloud architecture known to the corps. In a world of corporate firewalls and data streams, I build the interfaces of tomorrow — today.",
      aboutTitle: 'User.Profile',
      skillsTitle: 'Loaded.Modules',
      educationTitle: 'Training.Protocol',
      interestsTitle: 'Side.Processes',
      resumeTitle: 'Download.DataPack',
      resumeDesc: 'Access the complete data package of my professional firmware.',
      resumeButton: 'Execute Download',
      contactTitle: 'Establish.Connection',
      contactDesc: 'Initiate a secure connection through any of these network nodes.',
      heroButton1: 'Scan Profile',
      heroButton2: 'Open Channel',
      footerLine: 'All systems operational.',
      footerQuote: '"The future is already here — it\'s just not evenly distributed."',
    },
    particles: {
      type: 'matrix',
      color: '#00F0FF',
      count: 35,
    },
  },

  demonslayer: {
    id: 'demonslayer',
    name: 'Demon Slayer',
    icon: '🔥',
    background: bgDemonSlayer,
    profilePic: profileDemonSlayer,
    logo: logoDemonSlayer,
    fonts: {
      heading: "'Poppins', sans-serif",
      body: "'Noto Sans JP', 'Poppins', sans-serif",
    },
    colors: {
      '--theme-primary': '#00BFA5',
      '--theme-primary-hover': '#1DE9B6',
      '--theme-secondary': '#DC143C',
      '--theme-bg': '#0D1117',
      '--theme-bg-dark': '#060A0E',
      '--theme-card': 'rgba(13, 17, 23, 0.6)',
      '--theme-card-border': 'rgba(0, 191, 165, 0.25)',
      '--theme-card-hover-border': '#00BFA5',
      '--theme-card-hover-bg': 'rgba(0, 191, 165, 0.1)',
      '--theme-text': '#E6F1FF',
      '--theme-text-muted': '#8B949E',
      '--theme-text-subtle': '#6E7681',
      '--theme-glow': 'rgba(0, 191, 165, 0.5)',
      '--theme-nav-bg': 'rgba(6, 10, 14, 0.92)',
      '--theme-overlay-from': 'rgba(6, 10, 14, 0.75)',
      '--theme-overlay-via': 'rgba(13, 17, 23, 0.5)',
      '--theme-overlay-to': 'rgba(6, 10, 14, 0.92)',
      '--theme-ring': 'rgba(220, 20, 60, 0.4)',
      '--theme-gradient-from': '#060A0E',
      '--theme-gradient-to': '#0D1117',
    },
    copy: {
      tagline: '全集中 — Total Concentration',
      about: "I am Ajay Garg — a slayer of bugs and a master of the coding breathing forms. Just as Tanjiro trained relentlessly at the mountains to master Water Breathing, I have honed my skills through countless hours of disciplined practice. Every line of code I write flows like Water Breathing — First Form, precise and powerful. With the determination of the Demon Slayer Corps, I vanquish every bug, slash through every obstacle, and protect users with interfaces forged in the fires of passion and dedication.",
      aboutTitle: 'The Breathing Form',
      skillsTitle: 'Combat Techniques',
      educationTitle: 'Training Arc',
      interestsTitle: 'Off-Duty Pursuits',
      resumeTitle: 'The Scroll of Mastery',
      resumeDesc: 'Unroll the complete scroll documenting my training and conquests.',
      resumeButton: 'Unroll the Scroll',
      contactTitle: 'Join the Corps',
      contactDesc: 'Ready to fight alongside me? Reach out through these channels.',
      heroButton1: 'Begin Training',
      heroButton2: 'Join the Corps',
      footerLine: 'The blade that protects — through code.',
      footerQuote: '"No matter how many people you may lose, you have no choice but to go on living."',
    },
    particles: {
      type: 'petals',
      color: '#FF6B9D',
      count: 20,
    },
  },
};

export const themeOrder = ['got', 'harrypotter', 'netflix', 'cyberpunk', 'demonslayer'];

export default themes;
